#!/usr/bin/env python3

import argparse
import os

parser = argparse.ArgumentParser(description='Functionallity for the flask_template project')
command = parser.add_subparsers(dest="command")

build = command.add_parser('build')
lint = command.add_parser('lint')
run = command.add_parser('run')
test = command.add_parser('test')

args = parser.parse_args()

if args.command == 'build':
    print('Linting...')
    os.system('Tools/lib/lint')
    print('\nTesting...')
    os.system('Tools/lib/test')
elif args.command == 'lint':
    print('Linting...')
    os.system('Tools/lib/lint')
elif args.command == 'run':
    os.system('Tools/lib/run')
elif args.command == 'test':
    print('Testing...')
    os.system('Tools/lib/test')
