"""Make all dates non-nullable

Revision ID: 1166d01122bb
Revises: 0d852461326e
Create Date: 2021-12-07 19:43:49.921781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1166d01122bb'
down_revision = '0d852461326e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
                              existing_type=sa.DATETIME(),
                              existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False)
        batch_op.alter_column('created_at',
                              existing_type=sa.DATETIME(),
                              existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
                              existing_type=sa.DATETIME(),
                              nullable=False,
                              existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
                              existing_type=sa.DATETIME(),
                              nullable=False,
                              existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
                              existing_type=sa.DATETIME(),
                              nullable=True,
                              existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
                              existing_type=sa.DATETIME(),
                              nullable=True,
                              existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('created_at',
                              existing_type=sa.DATETIME(),
                              existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=True)
        batch_op.alter_column('updated_at',
                              existing_type=sa.DATETIME(),
                              existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=True)

    # ### end Alembic commands ###
